-- Generated by the database client.
CREATE TABLE app_config(
    id SERIAL NOT NULL,
    domain text,
    mid_server_key text,
    mid_client_key text,
    mid_merchant_id text,
    mid_base_url text,
    smtp_host text,
    smtp_port text,
    smtp_email text,
    smtp_pass text,
    smtp_from text,
    smtp_name text,
    meta_pixel text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE courses (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    instructor TEXT NOT NULL,
    category TEXT NOT NULL,
    level INTEGER NOT NULL,
    duration TEXT NOT NULL,
    price NUMERIC NOT NULL,
    description TEXT NOT NULL,
    thumbnail TEXT NOT NULL,
    video_preview TEXT NOT NULL,
    objectives TEXT[], -- Course learning objectives
    requirements TEXT[], -- Course prerequisites
    link_files TEXT,
    is_published BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Sections (previously topics) - Main course sections
CREATE TABLE sections (
    id SERIAL PRIMARY KEY,
    course_id INTEGER REFERENCES courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    position INTEGER NOT NULL, -- Order of sections in the course
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Lectures (previously subtopics) - Individual lessons within sections
CREATE TABLE lectures (
    id SERIAL PRIMARY KEY,
    section_id INTEGER REFERENCES sections(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    duration INTEGER, -- Duration in seconds
    position INTEGER NOT NULL, -- Order of lectures in the section
    is_preview BOOLEAN DEFAULT false, -- Whether this lecture is free preview
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Resources - Course materials and attachments
CREATE TABLE resources (
    id SERIAL PRIMARY KEY,
    lecture_id INTEGER REFERENCES lectures(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    file_type TEXT NOT NULL, -- video, pdf, doc, quiz, etc.
    content_url TEXT NOT NULL,
    file_size BIGINT, -- Size in bytes
    duration INTEGER, -- For video/audio content (in seconds)
    is_downloadable BOOLEAN DEFAULT true,
    position INTEGER NOT NULL, -- Order of resources in the lecture
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Quizzes - For assessment
CREATE TABLE quizzes (
    id SERIAL PRIMARY KEY,
    lecture_id INTEGER REFERENCES lectures(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    passing_score INTEGER NOT NULL,
    time_limit INTEGER, -- Time limit in minutes (optional)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Quiz questions
CREATE TABLE quiz_questions (
    id SERIAL PRIMARY KEY,
    quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    question_type TEXT NOT NULL, -- multiple_choice, true_false, etc.
    correct_answer TEXT NOT NULL,
    options TEXT[], -- Array of possible answers
    explanation TEXT, -- Explanation for the correct answer
    position INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);