-- Insert reviews for product_id 2
INSERT INTO reviews (product_id, name, rating, comment) VALUES
(2, 'Daru Pratama', 5, 'Setiap contoh prompt-nya kepake semua di dunia nyata.'),
(2, 'Sutan Kemba Pranowo', 4, 'Gue jadi bisa deliver kerjaan lebih cepet dari tim lain.'),
(2, 'Raden Halimah', 5, 'Buku ini bukan cuma ngajarin cara nanya, tapi cara mikir ulang.'),
(2, 'Bakiono Wibisono', 4, 'Lebih berani mulai ide baru karena tahu AI bisa back-up gue.'),
(2, 'Rahmi Tarihoran', 4, 'Gue pake buat ngajar, hasilnya jauh lebih interaktif sekarang.'),
(2, 'Anggabaya Damanik', 5, 'Buku ini bikin gue gak takut eksplorasi ide liar.'),
(2, 'Akarsana Uyainah', 5, 'Buku ini ngajarin cara ngajak AI ''kerja sama'' bukan ''nyuruh'' doang.'),
(2, 'Nardi Puspita', 5, 'Prompt bukan lagi hal susah setelah baca ini.'),
(2, 'Aditya Fujiati', 5, 'Mata gue kebuka: ternyata gue nanya ke AI selama ini salah arah.'),
(2, 'Violet Yolanda', 4, 'Beli buku ini bukan pengeluaran. Ini investasi.'),
(2, 'Hasim Zulkarnain', 4, 'Tanpa sadar, buku ini juga ngajarin cara jadi komunikator yang lebih baik.'),
(2, 'Lamar Haryanti', 4, 'Dulu bingung nanya ke ChatGPT, sekarang udah kayak punya asisten pribadi.'),
(2, 'Darmanto Zulaika', 5, 'Tiap role dapet bagian: guru, marketing, developer—semua relate.'),
(2, 'Zalindra Nasyiah', 4, 'Framework-nya bisa di-mix & match, fleksibel banget.'),
(2, 'Mila Firmansyah', 4, 'Gak cuma ngerti AI, tapi ngerti manusia juga.'),
(2, 'Agus Setiawan', 4, 'Sekarang gue bisa produce lebih banyak, dengan tenaga lebih sedikit.'),
(2, 'Vera Hasanah', 5, 'Akhirnya ngerti kenapa prompt gue dulu gak pernah berhasil.'),
(2, 'Chelsea Hassanah', 5, 'Gak ada isinya yang mubazir. Full daging semua.'),
(2, 'Xanana Yuliarti', 4, 'Udah banyak baca buku AI, tapi ini yang paling membumi.'),
(2, 'Ana Sitompul', 4, 'Top banget! Ini buku AI pertama yang relatable buat orang Indonesia.'),
(2, 'Sarah Lestari', 4, 'Satu kata: mind-blowing. Gak nyesel beli.'),
(2, 'Jaya Hasanah', 5, 'Buku ini ngasih gue kepercayaan diri buat eksplorasi ide tanpa takut salah.'),
(2, 'Eka Rajasa', 5, 'Gue jadi ngerti pola pikir di balik pertanyaan yang efektif.'),
(2, 'Catur Hasanah', 5, 'Isi bukunya kayak ''alat tempur'' buat digital age.'),
(2, 'Sakti Nugroho', 4, 'Dari skeptis, sekarang jadi evangelist AI di kantor.'),
(2, 'Karimah Saragih', 5, 'Buku ini bikin gue sadar: AI itu bukan saingan, tapi partner.'),
(2, 'Alika Nainggolan', 4, 'Pas banget buat era serba cepat dan serba multitasking.'),
(2, 'Ibun Natsir', 4, 'Tiap kali gue stuck, framework di buku ini bantu buka jalan.'),
(2, 'Jabal Mandala', 4, 'Framework ini semacam ''jurus ninja'' buat survive di era sekarang.'),
(2, 'Panca Kurniawan', 5, 'Framework-nya bikin AI kerasa kayak alat sulap modern.'),
(2, 'Bakiadi Widiastuti', 4, 'Bisa dipakai harian banget. Gak cuma sekali terus lupa.'),
(2, 'Kurnia Wahyudin', 5, 'Framework-nya bikin gue ngerti ''struktur mikir'' yang bisa dibaca AI.'),
(2, 'Kasiyah Hardiansyah', 5, 'Nanya ke AI sekarang jadi skill, dan buku ini ngajarin ilmunya.'),
(2, 'Nadine Pudjiastuti', 5, 'Berasa punya peta di dunia AI yang sebelumnya gelap buat gue.'),
(2, 'Azalea Haryanti', 4, 'Kerasa banget perbedaannya sebelum dan sesudah baca buku ini.'),
(2, 'Wisnu Halim', 5, 'Gue ngerasa lebih produktif tanpa harus kerja lebih lama.'),
(2, 'Emin Agustina', 5, 'Gue lebih bisa ngarahin AI ke output yang gue mau.'),
(2, 'Purwa Tamba', 5, 'Kalo semua orang baca ini, dunia kerja bakal jauh lebih efisien.'),
(2, 'Rosman Mulyani', 4, 'Framework-nya praktis banget, langsung bisa dipakai untuk kerjaan sehari-hari.'),
(2, 'Shania Dongoran', 4, 'Dijelasin pelan-pelan, tapi to the point. Cocok buat pemula.'),
(2, 'Emil Agustina', 4, 'Kaya banget ilmunya, tapi gak bikin mumet.'),
(2, 'Hani Lazuardi', 4, 'Framework-nya bikin gue makin tajam mikir dan nulis.'),
(2, 'Kala Mulyani', 4, 'Kalo semua guru baca ini, sistem belajar bakal berubah banyak.'),
(2, 'Adhiarja Prakasa', 5, 'Buku ini ngajarin cara mikir strategis, bukan cuma operatif.'),
(2, 'Yosef Maryadi', 5, 'Gak banyak teori, langsung praktik. Itu yang paling gue suka.'),
(2, 'Salimah Januar', 4, 'Setiap halaman berasa kayak ditampar halus—tajem tapi bikin sadar.'),
(2, 'Reksa Najmudin', 4, 'Gak perlu ngerti teknikal, yang penting ngerti tujuan. Buku ini ngajarin itu.'),
(2, 'Lanjar Waskita', 5, 'Buat guru kayak gue, buku ini life-saver banget buat bikin materi ajar.'),
(2, 'Carla Latupono', 4, 'Setiap bab rasanya kayak upgrade skill tanpa harus ikut workshop.'),
(2, 'Lanang Sitorus', 5, 'Gue bisa ngerjain 3x lebih banyak hal setelah pakai teknik di buku ini.'),
(2, 'Rachel Marbun', 4, 'Gak nyangka belajar AI bisa seseru ini.'),
(2, 'Queen Kuswandari', 5, 'Investasi kecil, tapi impact-nya gede buat kerjaan gue.'),
(2, 'Tgk. Pangestu Mulyani', 4, 'Setiap bab nambah kepercayaan diri buat eksplor tools digital.'),
(2, 'Aisyah Rajasa', 5, 'Sekarang gue kerja bareng AI kayak punya partner tim yang ngerti.'),
(2, 'Violet Sihombing', 5, 'AI jadi terasa lebih manusiawi gara-gara cara komunikasinya dibenerin.'),
(2, 'Cinthia Wahyuni', 4, 'Bisa langsung praktik dari bab pertama. Gak perlu nunggu tamat.'),
(2, 'Adika Adriansyah', 4, 'Kayak dikasih remote control buat otak digital bernama AI.'),
(2, 'Hari Saputra', 4, 'Recommended banget buat siapa pun yang mau adaptif di era sekarang.'),
(2, 'Yance Palastri', 5, 'Bikin prompt kayak nyusun puzzle sekarang. Ada polanya.'),
(2, 'Johan Laksmiwati', 4, 'Ini buku, tapi rasanya kayak punya mentor pribadi.'),
(2, 'Ganep Thamrin', 5, 'Baru bab awal aja udah langsung kerasa bedanya pas ngetik prompt.'),
(2, 'Sutan Atmaja Agustina', 5, 'Sekarang gue bisa bikin strategi marketing dalam 10 menit. Gila sih.'),
(2, 'Ismail Sudiati', 4, 'Simple, padat, dan penuh insight yang langsung bisa gue pake.'),
(2, 'Fitria Hutagalung', 4, 'Sekarang gue bisa bikin kode dasar tanpa buka Stack Overflow tiap menit.'),
(2, 'Endra Suwarno', 5, 'Kombinasi antara inspiratif dan teknis yang pas banget.'),
(2, 'Hani Zulkarnain', 4, 'Framework-nya bikin komunikasi ke AI jadi jelas dan fokus.'),
(2, 'Opan Wibisono', 4, 'Gue jadi lebih pede bikin konten, bikin kode, bahkan bikin modul ngajar.'),
(2, 'Kawaya Susanti', 5, 'Kalau kamu marketer, guru, atau programmer, buku ini wajib punya!'),
(2, 'Vicky Nuraini', 5, 'Tadinya skeptis, tapi sekarang malah ketagihan eksplorasi ide pakai AI.'),
(2, 'Irwan Susanti', 4, 'Gue pengen semua tim gue baca buku ini juga.'),
(2, 'Fitria Tamba', 4, 'Akhirnya ada buku AI yang relevan sama konteks kerja di Indonesia.'),
(2, 'Raina Handayani', 4, 'Kerasa banget penulisnya emang make sendiri, bukan sekadar nulis.'),
(2, 'Tina Rajasa', 5, 'Isi bukunya bikin semangat eksplor dan terus belajar.'),
(2, 'Dariati Rahayu', 5, 'Bisa bantu brainstorming juga, bukan cuma eksekusi.'),
(2, 'Cut Siska Laksita', 4, 'Gak cuma ngajarin cara nanya, tapi cara mikir juga dibentuk.'),
(2, 'Gatra Handayani', 4, 'Buat content creator, ini buku sakti.'),
(2, 'Dian Halim', 4, 'Efek baca buku ini: waktu kerja gue jadi jauh lebih efisien.'),
(2, 'Zelaya Hutagalung', 4, 'Ngajarin AI kayak ngajarin partner kerja. Bukan cuma mesin.'),
(2, 'Salsabila Melani', 5, 'Gaya bahasanya santai tapi dalam. Gak ngebosenin sama sekali.'),
(2, 'Rini Saptono', 4, 'Framework-nya simpel, tapi impactful banget.'),
(2, 'Salsabila Pratama', 4, 'Gue gak nyangka bisa bikin konten sekeren ini cuma dari prompt yang diajarin di buku.'),
(2, 'Drs. Mila Kusumo', 5, 'Buku ini ngajarin lo kerja cerdas, bukan keras.'),
(2, 'Purwadi Simbolon', 5, 'Satu buku—tapi hasilnya kerasa di banyak sisi hidup gue.'),
(2, 'Mila Halimah', 5, 'Framework-nya ngubah cara gue mikir soal komunikasi dengan AI.'),
(2, 'Cindy Laksmiwati', 4, 'Buku ini bikin gue ngulik AI lebih dalam tanpa takut pusing.'),
(2, 'Argono Natsir', 4, 'Gue gak nyangka bisa dapet insight sebanyak ini dari satu buku.'),
(2, 'Luhung Gunawan', 4, 'Framework-nya adaptif, bisa disesuaikan sama apapun kerjaan gue.'),
(2, 'Indah Haryanti', 5, 'Udah lama cari buku kayak gini—akhirnya ketemu juga.'),
(2, 'Salimah Wasita', 5, 'Desain bukunya simpel tapi isi kontennya luar biasa!'),
(2, 'Wulan Saragih', 5, 'Framework-nya nempel di kepala, gampang diingat dan dipakai.'),
(2, 'Aris Irawan', 5, 'Lo gak akan liat AI dengan cara yang sama lagi setelah baca buku ini.'),
(2, 'Prayogo Hassanah', 4, 'Setiap prompt-nya tajam. Berasa kayak skill baru nempel di otak.'),
(2, 'Dina Budiyanto', 5, 'Buku ini kayak ''cheatcode'' buat kerjaan digital gue.'),
(2, 'Ami Anggriawan', 5, 'Copywriting gue naik level gara-gara contoh prompt di buku ini.'),
(2, 'Margana Gunawan', 4, 'AI kayak punya kompas baru setelah baca ini.'),
(2, 'Laras Wijayanti', 5, 'Promosi produk gue lebih tajam karena prompt dari buku ini.'),
(2, 'Darijan Anggraini', 5, 'Ngebantu banget buat yang kerja serabutan di dunia digital.'),
(2, 'Zahra Haryanto', 5, 'Buku ini ngasih gue senjata buat kerja lebih cepet dan hasil lebih rapi.'),
(2, 'Farhunnisa Wibowo', 4, 'Makasih penulisnya udah bikin topik serumit ini jadi gampang dicerna.'),
(2, 'Karimah Suwarno', 4, 'Gue ngerasa lebih ''punya arah'' dalam setiap diskusi sama AI.'); 